planning:
  discretization:
    shoulder_pan_joint      0.017453292519943295
    shoulder_lift_joint     0.017453292519943295
    elbow_joint             0.017453292519943295
    wrist_1_joint           0.017453292519943295
    wrist_2_joint           0.017453292519943295
    wrist_3_joint           0.017453292519943295
  use_xyz_snap_mprim: false
  use_rpy_snap_mprim: false
  use_xyzrpy_snap_mprim: true
  use_short_dist_mprims: true
  xyz_snap_dist_thresh: 0.2
  rpy_snap_dist_thresh: 0.0
  xyzrpy_snap_dist_thresh: 0.0
  short_dist_mprims_thresh: 0.4
